In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import sys
sys.path.insert(0, '../Resources')
import MyFunctionsV4 as mfs

In [2]:
matches_file = "../CollectedData/match_list_92820.csv"
clubs_file = "../CollectedData/club_list_47422.csv"
matches_df = pd.read_csv(matches_file)
clubs_df = pd.read_csv(clubs_file)

In [3]:
clubs_df['club_id'] = clubs_df['club_id'].astype(int)

In [4]:
pd.options.display.max_columns = None
matches_df.head(3)

,pull_time,game_id,console,winning_club,h_club,h_club_id,h_goals,h_shots,h_shot_percent,h_passes_made,h_pass_attempts,h_pass_percent,h_tackles_made,h_tackle_attempts,h_tackle_percent,h_red_cards,h_players_in_match,h_forward,h_midfielder,h_defender,h_goalkeeper,h_any,h_season,h_round,opp_club,opp_club_id,opp_goals,opp_shots,opp_shot_percent,opp_passes_made,opp_pass_attempts,opp_pass_percent,opp_tackles_made,opp_tackle_attempts,opp_tackle_percent,opp_red_cards,opp_players_in_match,opp_forward,opp_midfielder,opp_defender,opp_goalkeeper,opp_any,opp_season,opp_round
0,2023-04-22 17:07:08,1940614734,xboxone,Bang Average FC,Bang Average FC,1940614,2,12,0.17,129,169,0.76,11,33,0.33,0,10,2,5,3,0,0,73,4,VFL Reading,229379,1,3,0.33,33,58,0.57,8,52,0.15,0,6,1,5,0,0,0,34,8
1,2023-04-22 17:07:08,17404994102,xboxone,Bang Average FC,Bang Average FC,1940614,2,5,0.40,104,128,0.81,9,65,0.14,1,10,2,5,3,0,0,73,3,Pendrizzy,17404994,1,1,1.00,95,121,0.79,8,24,0.33,0,6,3,3,0,0,0,10,2
2,2023-04-22 17:07:08,1940614732,xboxone,Bang Average FC,Bang Average FC,1940614,3,8,0.38,146,176,0.83,14,38,0.37,1,10,2,5,3,0,0,73,2,rock club,542709,1,3,0.33,44,63,0.70,9,30,0.30,0,6,2,2,2,0,0,170,10

In [5]:
clubs_df.head(3)

,pull_time,club_name,active,console,club_id,division,ten_match_record,total_games,wins,losses,draws,goals_scored,goals_per_match,goals_conceded,goals_conceded_per_match,goal_difference,promotions,holds,relegations,best_season_div,best_season_points,region,stadium,total_rank_points,league_points,cup_points,div_1_titles,other_div_titles,total_trophies
0,2023-04-20 21:41:00,Bang Average FC,Yes,xboxone,1940614,1.0,WWWWWWWWLD,643.0,501.0,76.0,66.0,1740.0,2.71,483.0,0.75,1257.0,9.0,64.0,0.0,1.0,25.0,British Isles,Estadio Santiago Bernabéu,19376,19376,0,44.0,8.0,52.0
1,2023-04-20 21:41:00,FootieXI,Yes,xboxone,4339359,1.0,WWWWWWWWWD,625.0,509.0,58.0,58.0,1943.0,3.11,640.0,1.02,1303.0,9.0,62.0,0.0,1.0,25.0,British Isles,Old Trafford,20309,20309,0,51.0,9.0,60.0
2,2023-04-20 21:41:00,NO TRUENES,Yes,xboxone,3705104,1.0,WWWWWWWLLD,577.0,478.0,59.0,40.0,1875.0,3.25,600.0,1.04,1275.0,9.0,57.0,0.0,1.0,25.0,Central America,ESTADIO DE TRONACION,19181,19181,0,49.0,9.0,58.0

In [6]:
home_club_match_stats = matches_df[['h_goals', 'h_shots', 'h_shot_percent', 'h_passes_made',
       'h_pass_attempts', 'h_pass_percent', 'h_tackles_made',
       'h_tackle_attempts', 'h_tackle_percent', 'h_red_cards',
       'h_players_in_match', 'h_forward', 'h_midfielder', 'h_defender',
       'h_goalkeeper', 'h_any', 'h_season', 'h_round']]

opp_club_match_stats = matches_df[['opp_goals', 'opp_shots', 'opp_shot_percent',
       'opp_passes_made', 'opp_pass_attempts', 'opp_pass_percent',
       'opp_tackles_made', 'opp_tackle_attempts', 'opp_tackle_percent',
       'opp_red_cards', 'opp_players_in_match', 'opp_forward',
       'opp_midfielder', 'opp_defender', 'opp_goalkeeper', 'opp_any',
       'opp_season', 'opp_round']]

clubs_df_subset = clubs_df[['club_name','club_id', 'division',
       'ten_match_record', 'total_games', 'wins', 'losses', 'draws',
       'goals_scored', 'goals_per_match', 'goals_conceded',
       'goals_conceded_per_match','region','total_rank_points',
       'div_1_titles','total_trophies']].fillna('region')

empty_value_df = pd.DataFrame(columns=['h_division',
       'h_ten_match_record', 'h_total_games', 'h_wins', 'h_losses', 'h_draws',
       'h_goals_scored', 'h_goals_per_match', 'h_goals_conceded',
       'h_goals_conceded_per_match','h_region','h_total_rank_points',
       'h_div_1_titles','h_total_trophies','opp_division',
       'opp_ten_match_record', 'opp_total_games', 'opp_wins', 'opp_losses', 'opp_draws',
       'opp_goals_scored', 'opp_goals_per_match', 'opp_goals_conceded',
       'opp_goals_conceded_per_match','opp_region','opp_total_rank_points',
       'opp_div_1_titles','opp_total_trophies'])

In [7]:
def club_match_data_assign(row, clubs_df_subset, home_club_match_stats, opp_club_match_stats):
    h_club_info = clubs_df_subset[clubs_df_subset['club_id'] == row.h_club_id].reset_index(drop=True)
    opp_club_info = clubs_df_subset[clubs_df_subset['club_id'] == row.opp_club_id].reset_index(drop=True)
    row.loc['h_division':'h_total_trophies'] = h_club_info.iloc[0, 2:].values
    row.loc['opp_division':'opp_total_trophies'] = opp_club_info.iloc[0, 2:].values
    return row

In [8]:
base_df = pd.concat([matches_df, empty_value_df], axis=1)

In [9]:
output_df = base_df.apply(club_match_data_assign, args=(clubs_df_subset, home_club_match_stats, opp_club_match_stats), axis=1)

In [10]:
output_df.columns

Index(['pull_time', 'game_id', 'console', 'winning_club', 'h_club',
       'h_club_id', 'h_goals', 'h_shots', 'h_shot_percent', 'h_passes_made',
       'h_pass_attempts', 'h_pass_percent', 'h_tackles_made',
       'h_tackle_attempts', 'h_tackle_percent', 'h_red_cards',
       'h_players_in_match', 'h_forward', 'h_midfielder', 'h_defender',
       'h_goalkeeper', 'h_any', 'h_season', 'h_round', 'opp_club',
       'opp_club_id', 'opp_goals', 'opp_shots', 'opp_shot_percent',
       'opp_passes_made', 'opp_pass_attempts', 'opp_pass_percent',
       'opp_tackles_made', 'opp_tackle_attempts', 'opp_tackle_percent',
       'opp_red_cards', 'opp_players_in_match', 'opp_forward',
       'opp_midfielder', 'opp_defender', 'opp_goalkeeper', 'opp_any',
       'opp_season', 'opp_round', 'h_division', 'h_ten_match_record',
       'h_total_games', 'h_wins', 'h_losses', 'h_draws', 'h_goals_scored',
       'h_goals_per_match', 'h_goals_conceded', 'h_goals_conceded_per_match',
       'h_region', 'h_total_rank_points', 'h_div_1_titles', 'h_total_trophies',
       'opp_division', 'opp_ten_match_record', 'opp_total_games', 'opp_wins',
       'opp_losses', 'opp_draws', 'opp_goals_scored', 'opp_goals_per_match',
       'opp_goals_conceded', 'opp_goals_conceded_per_match', 'opp_region',
       'opp_total_rank_points', 'opp_div_1_titles', 'opp_total_trophies'],
      dtype='object')

In [11]:
output_df.to_csv(f'../CollectedData/Merged_Club_Match_Data_{len(matches_df)}.csv')